apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
spec:
  selector:
    app: guestbook-ui
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
